### ISSUE TITLE
palworld server on raspberry pi 4b 8GB - Stuck on "Checking for SteamCMD updates"

### ISSUE THREAD

**Issue by syahpian** [nitrog0d/palworld-arm64#13]
device model: raspberry pi 4b 8gb
OS: ubuntu 22.04 64 bit server

hello, 

first of all, thank you for the arm64 server file

i have issue, the docker console seems stuck at "Checking for SteamCMD updates..."

not sure what do to next

regards

**Comment by nitrog0d** [comment]
Try waiting a little? That step takes a while if it's the first time, it should also show logging eventually.

**Comment by nitrog0d** [comment]
A friend told me Pi 4b can't even run SteamCMD 💀 My bad bro, try Oracle cloud free tier

**Comment by syahpian** [comment]
ok, i reply here again after 24 hour

regards
