### ISSUE TITLE
server config files empty?

### ISSUE THREAD

**Issue by Lucashamburguru** [nitrog0d/palworld-arm64#14]
wanted to change of the server config for game balance but the file ./Pal/Saved/Config/LinuxServer/PalWorldSettings.ini is empty. 
was following this https://tech.palworldgame.com/optimize-game-balance guide.

**Comment by Zhang-JiahangH** [comment]
; This configuration file is a sample of the default server settings.
; Changes to this file will NOT be reflected on the server.
; To change the server settings, modify Pal/Saved/Config/WindowsServer/PalWorldSettings.ini.
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(
Difficulty=None,
DayTimeSpeedRate=1.000000,
NightTimeSpeedRate=1.000000,
ExpRate=5.000000,
PalCaptureRate=1.000000,
PalSpawnNumRate=1.000000,
PalDamageRateAttack=1.000000,
PalDamageRateDefense=1.000000,
PlayerDamageRateAttack=1.000000,
PlayerDamageRateDefense=1.000000,
PlayerStomachDecreaceRate=1.000000,
PlayerStaminaDecreaceRate=1.000000,
PlayerAutoHPRegeneRate=1.000000,
PlayerAutoHpRegeneRateInSleep=1.000000,
PalStomachDecreaceRate=1.000000,
PalStaminaDecreaceRate=1.000000,
PalAutoHPRegeneRate=1.000000,
PalAutoHpRegeneRateInSleep=1.000000,
BuildObjectDamageRate=1.000000,
BuildObjectDeteriorationDamageRate=1.000000,
CollectionDropRate=1.000000,
CollectionObjectHpRate=1.000000,
CollectionObjectRespawnSpeedRate=1.000000,
EnemyDropItemRate=1.000000,
DeathPenalty=None,
bEnablePlayerToPlayerDamage=False,
bEnableFriendlyFire=False,
bEnableInvaderEnemy=True,
bActiveUNKO=False,
bEnableAimAssistPad=True,
bEnableAimAssistKeyboard=False,
DropItemMaxNum=3000,
DropItemMaxNum_UNKO=100,
BaseCampMaxNum=128,
BaseCampWorkerMaxNum=15,
DropItemAliveMaxHours=1.000000,
bAutoResetGuildNoOnlinePlayers=False,
AutoResetGuildTimeNoOnlinePlayers=72.000000,
GuildPlayerMaxNum=20,
PalEggDefaultHatchingTime=1.000000,
WorkSpeedRate=1.000000,
bIsMultiplay=False,
bIsPvP=False,
bCanPickupOtherGuildDeathPenaltyDrop=False,
bEnableNonLoginPenalty=True,
bEnableFastTravel=True,
bIsStartLocationSelectByMap=True,
bExistPlayerAfterLogout=False,
bEnableDefenseOtherGuildPlayer=False,
CoopPlayerMaxNum=4,
ServerPlayerMaxNum=32,
ServerName="Default Palworld Server",
ServerDescription="",
AdminPassword="",
ServerPassword="",
PublicPort=8211,
PublicIP="",
RCONEnabled=False,
RCONPort=25575,
Region="",
bUseAuth=True,
BanListURL="https://api.palworldgame.com/api/banlist.txt"
)

Hope this can help (I don't know how to restart the server though lol)

**Comment by Lucashamburguru** [comment]
doesn't seem like the settings had any effect, but thank you anyways =)

**Comment by lbbboy** [comment]
```
docker compose down

cat pwserver/palworld/DefaultPalWorldSettings.ini > palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini

docker compose up -d
```

**Comment by Lucashamburguru** [comment]
> ```
> docker compose down
> 
> cat pwserver/palworld/DefaultPalWorldSettings.ini > palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
> 
> docker compose up -d
> ```

seems to have worked, thanks. strangely all the other files in that directory were empty too.

**Comment by Zhang-JiahangH** [comment]
Just to explain this a little bit better:

// stop the server
docker compose down

// assume you are currently at the folder where you put the docker-compose.yml
// paths are relative path
cat palworld/DefaultPalWorldSettings.ini > palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini

// now you can modify the PalWorldSettings.ini file to config the server
// restart the server
docker compose up -d
