### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by jwxxzc** [nitrog0d/palworld-arm64#18]
Hi I currently can't connect to my server after setup, could I please receive some help.
This is what I see in the terminal.

ubuntu@instance-20240130-0329:~/servers/palworld$ sudo docker compose up
[+] Running 2/1
 ✔ Network palworld_default   Created                                      0.1s
 ✔ Container palworld-server  Created                                      0.1s
Attaching to palworld-server
palworld-server  | Checking for SteamCMD updates...
palworld-server  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
palworld-server  | ILocalize::AddFile() failed to load file "public/steambootstr                          apper_english.txt".
palworld-server  | [  0%] Checking for available update...
palworld-server  | [----] Downloading update (0 of 59782 KB)...
palworld-server  | [  0%] Downloading update (0 of 59782 KB)...
palworld-server  | [  0%] Downloading update (0 of 59782 KB)...
palworld-server  | [  0%] Downloading update (2884 of 59782 KB)...
palworld-server  | [  4%] Downloading update (7004 of 59782 KB)...
palworld-server  | [ 11%] Downloading update (9550 of 59782 KB)...
palworld-server  | [ 15%] Downloading update (12261 of 59782 KB)...
palworld-server  | [ 20%] Downloading update (14711 of 59782 KB)...
palworld-server  | [ 24%] Downloading update (17161 of 59782 KB)...
palworld-server  | [ 28%] Downloading update (19612 of 59782 KB)...
palworld-server  | [ 32%] Downloading update (22081 of 59782 KB)...
palworld-server  | [ 36%] Downloading update (24807 of 59782 KB)...
palworld-server  | [ 41%] Downloading update (27275 of 59782 KB)...
palworld-server  | [ 45%] Downloading update (29738 of 59782 KB)...
palworld-server  | [ 49%] Downloading update (32182 of 59782 KB)...
palworld-server  | [ 53%] Downloading update (34656 of 59782 KB)...
palworld-server  | [ 57%] Downloading update (37380 of 59782 KB)...
palworld-server  | [ 62%] Downloading update (39852 of 59782 KB)...
palworld-server  | [ 66%] Downloading update (42057 of 59782 KB)...
palworld-server  | [ 70%] Downloading update (43293 of 59782 KB)...
palworld-server  | [ 72%] Downloading update (44645 of 59782 KB)...
palworld-server  | [ 74%] Downloading update (45861 of 59782 KB)...
palworld-server  | [ 76%] Downloading update (47077 of 59782 KB)...
palworld-server  | [ 78%] Downloading update (48429 of 59782 KB)...
palworld-server  | [ 81%] Downloading update (49648 of 59782 KB)...
palworld-server  | [ 83%] Downloading update (50868 of 59782 KB)...
palworld-server  | [ 85%] Downloading update (52090 of 59782 KB)...
palworld-server  | [ 87%] Downloading update (53422 of 59782 KB)...
palworld-server  | [ 89%] Downloading update (54637 of 59782 KB)...
palworld-server  | [ 91%] Downloading update (55852 of 59782 KB)...
palworld-server  | [ 93%] Downloading update (57196 of 59782 KB)...
palworld-server  | [ 95%] Downloading update (58422 of 59782 KB)...
palworld-server  | [ 97%] Downloading update (59636 of 59782 KB)...
palworld-server  | [ 99%] Downloading update (59782 of 59782 KB)...
palworld-server  | [100%] Download Complete.
palworld-server  | [----] Applying update...
palworld-server  | [----] Extracting package...
palworld-server  | [----] Extracting package...
palworld-server  | [----] Extracting package...
palworld-server  | [----] Extracting package...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Cleaning up...
palworld-server  | [----] Update complete, launching...
palworld-server  | CWorkThreadPool::~CWorkThreadPool: work processing queue not                           empty: 6 items discarded.
palworld-server  | tid(27) burning pthread_key_t == 0 so we never use it
palworld-server  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
palworld-server  | Logging directory: '/home/steam/Steam/logs'
palworld-server  | /tmp/dumps insufficient permissions - delete and recreate
palworld-server  | [  0%] Checking for available updates...
palworld-server  | [----] Verifying installation...
palworld-server  | [  0%] Downloading update...
palworld-server  | [  0%] Checking for available updates...
palworld-server  | [----] Download complete.
palworld-server  | [----] Extracting package...
palworld-server  | [----] Extracting package...
palworld-server  | [----] Extracting package...
palworld-server  | [----] Extracting package...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Installing update...
palworld-server  | [----] Cleaning up...
palworld-server  | [----] Update complete, launching Steamcmd...
palworld-server  | tid(39) burning pthread_key_t == 0 so we never use it
palworld-server  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
palworld-server  | Logging directory: '/home/steam/Steam/logs'
palworld-server  | [  0%] Checking for available updates...
palworld-server  | [----] Verifying installation...
palworld-server  | Steam Console Client (c) Valve Corporation - version 17051083                          07
palworld-server  | -- type 'quit' to exit --
palworld-server  | Loading Steam API...dlmopen steamservice.so failed: steamserv                          ice.so: cannot open shared object file: No such file or directory
palworld-server  | OK
palworld-server  | Checking for updates... (Do not panic if it looks stuck)
palworld-server  | tid(62) burning pthread_key_t == 0 so we never use it
palworld-server  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
palworld-server  | Logging directory: '/home/steam/Steam/logs'
palworld-server  | [  0%] Checking for available updates...
palworld-server  | [----] Verifying installation...
palworld-server  | Steam Console Client (c) Valve Corporation - version 17051083                          07
palworld-server  | -- type 'quit' to exit --
palworld-server  | Loading Steam API...dlmopen steamservice.so failed: steamserv                          ice.so: cannot open shared object file: No such file or directory
palworld-server  | OK
palworld-server  |
palworld-server  | Connecting anonymously to Steam Public...OK
palworld-server  | Waiting for client config...OK
palworld-server  | Waiting for user info...OK
palworld-server  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
palworld-server  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
palworld-server  |  Update state (0x5) verifying install, progress: 7.59 (170591                          074 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 11.76 (26426                          3583 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 14.94 (33579                          8280 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 19.49 (43814                          4240 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 24.02 (53992                          0603 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 28.58 (64257                          6797 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 32.86 (73868                          5435 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 36.45 (81948                          3768 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 38.91 (87469                          8177 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 41.43 (93133                          5676 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 43.86 (98605                          4471 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 46.09 (10360                          35181 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 49.26 (11074                          95644 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 53.78 (12089                          07513 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 58.33 (13113                          59307 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 62.88 (14135                          26401 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 67.48 (15169                          77271 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 72.05 (16197                          11077 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 76.59 (17217                          69689 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 81.15 (18241                          98494 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 85.67 (19258                          86970 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 90.23 (20283                          85428 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 94.79 (21309                          75686 / 2248045559)
palworld-server  |  Update state (0x5) verifying install, progress: 99.31 (22326                          17198 / 2248045559)
palworld-server  | Success! App '2394010' fully installed.
palworld-server  | Starting server... You can safely ignore Steam errors! (Also                           the server has pretty much 0 logging, so just try connecting to it)
palworld-server  | /home/steam/.fex-emu/RootFS/Ubuntu_22_04/usr/bin/chmod: chang                          ing permissions of '/palworld/Pal/Binaries/Linux/PalServer-Linux-Test': Operatio                          n not permitted
palworld-server  | dlopen failed trying to load:
palworld-server  | steamclient.so
palworld-server  | with error:
palworld-server  | steamclient.so: cannot open shared object file: No such file                           or directory
palworld-server  | [S_API] SteamAPI_Init(): Loaded '/home/steam/.steam/sdk64/ste                          amclient.so' OK.  (First tried local 'steamclient.so')
palworld-server  | Shutdown handler: initalize.
palworld-server  | - Existing per-process limit (soft=1048576, hard=1048576) is                           enough for us (need only 1048576)
palworld-server  | Increasing per-process limit of core file size to infinity.
palworld-server  | - Existing per-process limit (soft=18446744073709551615, hard                          =18446744073709551615) is enough for us (need only 18446744073709551615)
palworld-server  | CAppInfoCacheReadFromDiskThread took 27 milliseconds to initi                          alize
palworld-server  | Setting breakpad minidump AppID = 2394010
palworld-server  | [S_API FAIL] Tried to access Steam interface SteamUser021 bef                          ore SteamAPI_Init succeeded.
palworld-server  | [S_API FAIL] Tried to access Steam interface SteamFriends017                           before SteamAPI_Init succeeded.
palworld-server  | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERF                          ACE_VERSION008 before SteamAPI_Init succeeded.
palworld-server  | [S_API FAIL] Tried to access Steam interface SteamNetworkingU                          tils004 before SteamAPI_Init succeeded.

**Comment by sa-shiro** [comment]
did you open the port? 8211, u also need to open it in the oracle cloud security list

maybe give it some time, i had this issue too, i couldn't connect to it and now somehow it works again
https://github.com/nitrog0d/palworld-arm64/issues/17

**Comment by catsinasippycup** [comment]
ran into this issue as well, had to open port 8211.

**Comment by jwxxzc** [comment]
> did you open the port? 8211, u also need to open it in the oracle cloud security list
> 
> maybe give it some time, i had this issue too, i couldn't connect to it and now somehow it works again #17

Thank you very much, oracle security list, had to be opened up there, I appreciate your response
