### ISSUE TITLE
steamclient.so error

### ISSUE THREAD

**Issue by noamyoyo** [nitrog0d/palworld-arm64#19]
Hi. tried to setup using docker compose and got the following error:
![palworld-error](https://github.com/nitrog0d/palworld-arm64/assets/24484589/6d4f4db0-4aca-43d5-87d4-9ea2dedaf62f)

docker compose looks like so, running with portainer:
![image](https://github.com/nitrog0d/palworld-arm64/assets/24484589/6712ac2d-99d2-409c-9e53-a03ed2fc70dc)

ran the chown commands before setup and created directory as instructed:
![image](https://github.com/nitrog0d/palworld-arm64/assets/24484589/b6c85444-ee7d-4e81-bb86-30314234dba8)

Tried multiple times, no dice. 
Any help would be appericiated! 
@nitrog0d 

*Edit* 
Tried to build from source, using the dockerfile, still same error

**Comment by noamyoyo** [comment]
@nitrog0d made a mistake and opened a wrong port protcol, tcp instead of udp, all works now thanks lol

**Comment by nitrog0d** [comment]
![Screenshot_20240130-144338_GitHub.png](https://github.com/nitrog0d/palworld-arm64/assets/31241699/01d21e5b-eaf6-4e21-9ba4-05272df7e978)

Idk man clearly says udp here...and works for everyone else normally too........
