### ISSUE TITLE
S_API FAIL

### ISSUE THREAD

**Issue by Yoloretro** [nitrog0d/palworld-arm64#26]
![Error](https://github.com/nitrog0d/palworld-arm64/assets/62492534/a11952a1-f988-4437-960f-92ffc3df4a85)
I'm stuck here and I don't know how I can fix it, any solution?
![error2](https://github.com/nitrog0d/palworld-arm64/assets/62492534/e17019a1-c4c2-4ea0-8c57-aa8544dbfaef)
I also can't start the server with /home/steam/init-server.sh because it gives me an error, I already did chown -R, and it doesn't work

Ports:
![ports2](https://github.com/nitrog0d/palworld-arm64/assets/62492534/a3b309a3-c4a3-4311-b503-48c72b184f8d)
![ports](https://github.com/nitrog0d/palworld-arm64/assets/62492534/b9bc1475-39a3-49cf-863d-4b4374949e3e)

**Comment by Yoloretro** [comment]
![error2](https://github.com/nitrog0d/palworld-arm64/assets/62492534/a61a06d1-0504-4049-8090-8b15a567eaf9)
I also can't start the server with /home/steam/init-server.sh because it gives me an error, I already did chown -R, and it doesn't work

**Comment by Yoloretro** [comment]
Solved: Fixed bug Port suddenly opened fine, port was causing problems.

**Comment by Yoloretro** [comment]
Solved: Fixed bug Port suddenly opened fine, port was causing problems.

**Comment by ItzPeto** [comment]
I'm facing this exact issue, what did you do?
