### ISSUE TITLE
"I do not have read/write permissions to /palworld!"

### ISSUE THREAD

**Issue by jwc339** [nitrog0d/palworld-arm64#3]
Thank you for creating such great material.
However, when I try to run it, it doesn't work as shown below.
This is the details of what I did.

1. sudo apt-get install docker.io
2. sudo ln -sf /usr/bin/docker.io /usr/local/bin/docker
3. docker run -d \
     --name palworld-server \
     -p 8211:8211/udp\
     -p 27015:27015/udp \
     -v $(pwd)/game:/palworld/ \
     -e PLAYERS=32 \
     -e PORT=8211 \
     -e COMMUNITY=false \
     --restart unless-stopped \
     nitrog0d/palworld-arm64

I proceeded like this, but at first PORT was displayed, but after that, STATUS kept showing Restarting.
Could you please let me know if there is anything I did wrong?
![캡처](https://github.com/nitrog0d/palworld-arm64/assets/59954350/1f82fe87-0005-447b-975f-ea0d710b1e3c)

**Comment by nitrog0d** [comment]
Try to check logs of the container?

**Comment by RhanCandia** [comment]
@jwc339 Did you create the palworld directory? And after that you need to `chown 777 ./palword`. If you don't the containers will have permission errors.

**Comment by jwc339** [comment]
> @jwc339 Did you create the palworld directory? And after that you need to `chown 777 ./palword`. If you don't the containers will have permission errors.

Could you explain a little more about what to do?
Thank you for your reply.

**Comment by jwc339** [comment]
> Try to check logs of the container? Remove -d or run `docker logs`
Thanks for your reply.
The log is as follows.

ERROR: I do not have read/write permissions to /palworld! Please run "chown -R 1000:1000 palworld/" on host machine, then try again.

![image](https://github.com/nitrog0d/palworld-arm64/assets/59954350/d5e47025-1452-4f81-a12e-4d05ef5d5ba9)

**Comment by jwc339** [comment]
Thank you. Run.


> Step 2 in the Getting Started guide: https://github.com/nitrog0d/palworld-arm64?tab=readme-ov-file#getting-started
> 
> Before you run the docker command first create a directory `palworld` and then run `chmod 777 ./palworld`.
> 
> Then you can run the same docker command you used.

The server was successfully launched!!
thank you
The order I followed is as follows:
Connect using Putty.exe.

1. sudo su
2. mkdir palworld
3. chmod 777 palworld
4. chown -R 1000:1000 palworld/
5. vi docker-compose.yml
6. version: '3.9'
services:
   palworld-server:
     image: 'nitrog0d/palworld-arm64:latest'
     container_name: 'palworld-server'
     ports:
       - '8211:8211/udp'
     environment:
       - ALWAYS_UPDATE_ON_START=true
       -MULTITHREAD_ENABLED=true
       - COMMUNITY_SERVER=false
     restart: 'unless-stopped'
     volumes:
       - './palworld:/palworld'
7. docker-compose up -d
8. docker ps
Confirmed with .

thank you!
